server:
  port: 8899
  address: 127.0.0.1
spring:
    profiles:
        active: dev
    application:
        name: external-server
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        url: jdbc:oracle:thin:@172.99.110.78:1521:eppenpf
        username: eppenpf_dcs
        password: eppenpf_dcs
        type: com.alibaba.druid.pool.DruidDataSource
        druid:
          max-wait: 600000
    jpa:
        show-sql: true
        hibernate:
          ddl-auto: update
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: Hongkong
    thymeleaf:
        check-template: true
        encoding: UTF-8
        prefix: classpath:/templates/
        suffix: .html
        servlet:
          content-type: text/html
        cache: false
        mode: LEGACYHTML5
logback:
    logdir: logs
    appname: external-server